-- GENERATED by tools/build-migrations.mjs from supabase/migrations/. Do not edit — run
-- `npm run build:migrations` instead (docs/migrations.md).
--
-- Every migration, oldest first. Each one is re-runnable, so this whole file can be pasted into the
-- dashboard's SQL Editor to build the schema on a fresh project.

-- ===== 20260902000002_profiles.sql =====

-- One row per user, created by a trigger so a profile always exists by the time the app reads
-- one, and deleted by the cascade when the account goes.

-- Holds functions that must never be reachable over HTTP: PostgREST publishes `public` (and
-- `graphql_public`) and nothing else, so a function in here has no /rest/v1/rpc/ URL to attack.
create schema if not exists private;

create table if not exists public.profiles (
  -- Not a key this schema chooses: it is auth.users.id. Random uuids fragment an index, but that
  -- trade was made in auth.users, and matching it is what lets `on delete cascade` do the cleanup.
  id uuid primary key references auth.users (id) on delete cascade,

  -- No `email` column on purpose. auth.users.email is the source of truth and the client already
  -- holds it as session.user.email; a copy here goes stale the moment someone changes their
  -- address, and keeping it in step needs a second trigger that nobody remembers to write.
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

-- Every table you add needs this line of its own. The next migration tries to install an event
-- trigger that would also catch it, but that needs superuser and hosted Supabase's `postgres` role is
-- not one — there it only warns and the trigger never exists (verified 2026-09-13), so it is no
-- substitute for writing the line. Without it PostgREST serves the whole table to anyone holding the
-- publishable key, which ships in the app bundle. The dashboard's Security Advisor flags the tables
-- that are missing it.
alter table public.profiles enable row level security;

-- Deliberately NOT `force row level security`, which is otherwise the stricter default worth
-- reaching for. Forcing it subjects the table owner to the policies too, and handle_new_user below
-- inserts as the owner during signup — a moment when there is no JWT, so auth.uid() is null and
-- profiles_insert_own would reject the row that signup exists to create.

-- Every policy is scoped `to authenticated` so it is never even evaluated for anon, and every
-- auth.uid() is wrapped in a select. Unwrapped, it is called once per row scanned; wrapped, the
-- planner runs it once as an InitPlan and reuses the result.
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select to authenticated
  using ((select auth.uid()) = id);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
  for insert to authenticated
  with check ((select auth.uid()) = id);

-- `using` decides which rows may be updated, `with check` what they may be updated *to*. Without
-- the second one a user could hand their row to somebody else by rewriting its id.
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- No delete policy, so no client can delete a profile directly. The row goes when the account
-- does, through the cascade on auth.users that delete_current_user below triggers.

-- No index on id: the primary key already is one.


-- Creates the profile row for a new signup.
--
-- security definer because the insert has to bypass RLS — see the note above about auth.uid()
-- being null inside the signup transaction — and because the caller here is GoTrue, not the user.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    -- Google and Facebook both land here through signInWithIdToken / the browser flow, and both
    -- populate these two keys. nullif keeps an empty string from masquerading as a set name.
    -- The jsonb ->> operator is in pg_catalog, so it still resolves under the empty search_path.
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke execute on function private.handle_new_user() from public, anon, authenticated, service_role;

-- Revoking EXECUTE does not stop this. Postgres checks EXECUTE on a trigger function when the
-- trigger is created, not each time it fires, so the trigger keeps working while the function
-- stays uncallable by hand.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();


-- Self-service account deletion, which the App Store requires of any app that can create an
-- account (Guideline 5.1.1(v)). Called from deleteAccount() in src/lib/auth.ts.
--
-- This one is in `public` because it is meant to be reachable — it is the app's own API, and
-- PostgREST only publishes `public`. Which is exactly why the grants below are not optional.
create or replace function public.delete_current_user()
returns void
language sql
security definer
set search_path = ''
as $$
  -- The only row this can ever touch is the caller's own. For an unauthenticated caller auth.uid()
  -- is null and `id = null` matches nothing, so the failure mode is deleting zero rows; the grant
  -- below is what actually keeps anon out. public.profiles goes with it through the cascade.
  delete from auth.users where id = (select auth.uid());
$$;

-- Without this, `create function` in a Supabase project leaves the function callable at
-- POST /rest/v1/rpc/delete_current_user by anyone holding the anon key — which ships inside the
-- app binary. Supabase's default privileges grant EXECUTE to anon, authenticated and service_role
-- directly, so all three have to be named; revoking from PUBLIC alone would not reach them.
revoke execute on function public.delete_current_user() from public, anon, authenticated, service_role;
grant execute on function public.delete_current_user() to authenticated;


-- ===== 20260902000003_rls_auto_enable.sql =====

-- Enables RLS automatically on every table created in `public` from here on.
--
-- This runs. It is a normal migration and `supabase db push` applies it.
--
--
-- What it does
--
-- Installs a DDL event trigger that runs `alter table ... enable row level security` on every table
-- created in `public` from then on. Forgetting that on one table is the most common way a Supabase
-- project leaks data: PostgREST publishes the table over HTTP the moment it exists, the publishable
-- key ships inside the app bundle where anyone can read it out, and with no policy in force every
-- row is world-readable.
--
--
-- It is a safety net, not the mechanism
--
-- Keep writing `alter table ... enable row level security` explicitly in every migration. Two
-- reasons this trigger cannot be relied on alone:
--
--   1. It needs superuser to install (see the DO block at the bottom), and on hosted Supabase it
--      does NOT install. The project's `postgres` role is not a superuser (`rolsuper` is false), so
--      `create event trigger` fails with `permission denied to create event trigger` — verified on
--      this project's hosted database on 2026-09-13. The block turns that into a warning, so
--      `supabase db push` succeeds, the SQL Editor reports "Success", and the trigger is simply not
--      there. private.rls_auto_enable() below is still created, with nothing calling it. The
--      trigger only exists on a local `supabase start` stack, so on a hosted project the explicit
--      line is the only thing that turns RLS on.
--   2. It is invisible. `\d your_table` does not mention it, the migration that created that table
--      does not mention it, and nothing leads a reader from an unexpectedly empty result back to
--      this file.
--
-- RLS with no policies is deny-all, so when it does fire the failure mode is a query returning
-- nothing — loud, and one `create policy` away from fixed.
--
--
-- What still reports the gap
--
-- The dashboard's Security Advisor (Advisors -> Security) reports `rls_disabled_in_public` for any
-- table this missed. `supabase db lint` is NOT this — that command only type-checks plpgsql.

create schema if not exists private;

-- The function lives in `private`, not `public`. PostgREST only publishes `public` (and
-- `graphql_public`), so nothing in here has a /rest/v1/rpc/ URL at all. The revoke below is a
-- second lock on the same door.
create or replace function private.rls_auto_enable()
returns event_trigger
language plpgsql
security definer
-- Pinned, and the body fully qualified because of it. An unqualified name inside a security
-- definer function resolves against the *caller's* search_path, so a caller who creates their own
-- `format` or their own table and points the path at it gets that object executed with this
-- function's owner privileges. Empty is safe for the calls below: pg_catalog is searched
-- implicitly even when it is not on the path.
set search_path = ''
as $$
declare
  cmd record;
begin
  for cmd in
    select *
    from pg_catalog.pg_event_trigger_ddl_commands()
    where object_type in ('table', 'partitioned table')
      and schema_name = 'public'
  loop
    begin
      -- object_identity arrives already schema-qualified and quoted, so %s is right here and %I
      -- would quote it a second time.
      execute pg_catalog.format('alter table %s enable row level security', cmd.object_identity);
    exception
      -- An event trigger that raises aborts the CREATE TABLE that fired it. A table that resists
      -- RLS is worth a warning, not a migration that cannot run.
      when others then
        raise warning 'rls_auto_enable: could not enable RLS on %', cmd.object_identity;
    end;
  end loop;
end;
$$;

-- Not redundant with the schema choice. Supabase ships default privileges that grant EXECUTE on
-- new functions to anon, authenticated and service_role *directly* — not through PUBLIC — so
-- revoking from PUBLIC alone would leave three live grants behind.
revoke execute on function private.rls_auto_enable() from public, anon, authenticated, service_role;

-- CREATE EVENT TRIGGER requires superuser. The local `supabase start` stack has it; hosted Supabase's
-- `postgres` role does not, so on a hosted project this block always lands in the exception branch.
-- That must not take the whole migration down: every table's own migration enables RLS explicitly,
-- so this is defence in depth where it installs, not the only defence.
do $$
begin
  execute 'drop event trigger if exists ensure_rls';
  execute 'create event trigger ensure_rls on ddl_command_end
             when tag in (''CREATE TABLE'', ''CREATE TABLE AS'', ''SELECT INTO'')
             execute function private.rls_auto_enable()';
exception
  when insufficient_privilege then
    raise warning
      'ensure_rls not installed: creating an event trigger needs superuser. Every table still sets RLS explicitly.';
end;
$$;


-- ===== 20260908000000_drop_legacy_catalog_functions.sql =====

-- Drop the leftover book-catalog functions.
--
-- The hosted project this repo points at was previously used by an unrelated library
-- catalog app. Its tables are already gone, but nine functions survived in `public`
-- with no caller and no dependent object: `pg_trigger` holds only this project's own
-- `on_auth_user_created`, and `fn_set_updated_at` is attached to nothing.
--
-- They are not dead weight only. `public` is the schema PostgREST publishes, so each
-- one was a live `/rest/v1/rpc/<name>` URL reachable with the publishable key that
-- ships inside the app bundle. Three were `security definer` with `execute` still
-- granted to `anon`:
--
--   * `verify_user_password` (both overloads) answered password guesses without a
--     session — an unauthenticated credential-testing endpoint.
--   * `insert_book_encrypted` wrote rows as the owner.
--
-- None of the nine pinned `search_path`, so an unqualified name in the body resolved
-- against the caller's — the escalation CLAUDE.md section 6.2 rule 2 describes.
--
-- `if exists` because a clone pointed at a fresh Supabase project never had these,
-- and `supabase db push` has to succeed there too. No `cascade`: if some object does
-- turn out to depend on one of these, this migration should fail loudly rather than
-- take that object with it.
--
-- No revert file (docs/migrations.md rule 2): the bodies of what this drops are not in
-- the repo, and restoring them would reopen the endpoints described above.
-- no-revert: drop-only; its revert would restore leftover functions from an unrelated project

drop function if exists public.verify_user_password(p_email text, p_password text, p_enc_key text);
drop function if exists public.verify_user_password(p_email_fingerprint text, p_password text);
drop function if exists public.insert_book_encrypted(
  p_enc_key text, p_title text, p_responsibility text, p_variant_title text,
  p_parallel_title text, p_main_creator text, p_contributors text, p_corporate text,
  p_place_of_publication text, p_publisher text, p_date_of_publication text,
  p_extent_of_text text, p_edition text, p_illustration text, p_series text,
  p_isbn text, p_subject_typical text, p_subject_personal text,
  p_call_number_prefix text, p_call_number text, p_material_types text[],
  p_accession text, p_language text, p_library_location text,
  p_electronic_access text, p_cover_image_file text, p_vol_copy integer,
  p_entered_by text, p_date_entered date, p_update_date date, p_vocabulary text,
  p_localization text, p_collection_types text[]
);
drop function if exists public.encrypt_field(plaintext text, enc_key text);
drop function if exists public.decrypt_field(ciphertext bytea, enc_key text);
drop function if exists public.hash_password(plain text);
drop function if exists public.verify_password(plain text, stored_hash text);
drop function if exists public.sha256_hex(val text);
drop function if exists public.fn_set_updated_at();


-- ===== 20260908131200_merchants.sql =====

-- The tenant table. A merchant is the business whose rows are being protected; a user account is a
-- person. Today one merchant has exactly one user, and `merchants.owner_id` *is* the membership —
-- see docs/tenancy.md §3 for why `merchant_members` is deliberately not built yet.
--
-- This is also the answer to the open question in docs/tenancy.md §5, "who creates the merchant
-- row?": not a trigger. An explicit onboarding step — CreateSystemModal in
-- src/features/merchants/ — because a staff member joining an existing merchant must not silently
-- create a second one.

-- Already created by 20260902000002_profiles.sql. Repeated because a migration that depends on a
-- schema should say so rather than inherit it by file ordering.
create schema if not exists private;

-- An enum rather than `text` + a check constraint. Both cost one migration to add a value and both
-- need the same data migration to remove one, so the tie is broken by what reaches the client:
-- an enum generates a real union in src/lib/database.types.ts, which is what lets
-- CATEGORY_META[row.category] compile with no type assertion. `text` generates `string`, which
-- forces exactly the assertion .oxlintrc.json rejects (require-safety-comment-for-type-assertion,
-- no-unsafe-dictionary-type).
--
-- Adding a category later is `alter type public.store_category add value '…'` in a migration of its
-- own: Postgres will not let the same transaction use a value it just added.
do $$
begin
  if not exists (
    select 1 from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'store_category' and n.nspname = 'public'
  ) then
    create type public.store_category as enum (
      'restaurant', 'cafe', 'clothing', 'grocery', 'bakery',
      'electronics', 'pharmacy', 'bookstore', 'fitness', 'other'
    );
  end if;
end
$$;

create table if not exists public.merchants (
  id uuid primary key default gen_random_uuid(),

  -- The cascade is what makes public.delete_current_user() complete: deleting the auth.users row
  -- takes the profile and every merchant with it, so account deletion needs no extra statement.
  owner_id uuid not null references auth.users (id) on delete cascade,

  name text not null,
  description text,
  category public.store_category not null,
  created_at timestamptz not null default now(),

  -- btrim so a name of pure whitespace fails. The 255 on description is the number the
  -- CreateSystemModal counter shows the user; the same bound lives in
  -- src/features/merchants/schema.ts so the form reports it before a round trip, and here so the
  -- database is the one that actually enforces it.
  constraint merchants_name_length check (length(btrim(name)) between 1 and 80),
  constraint merchants_description_length check (description is null or length(description) <= 255)
);

-- Its own line, per the note in 20260902000002_profiles.sql. The event trigger in
-- 20260902000003_rls_auto_enable.sql would also catch this table where it installs, but installing it
-- needs superuser — so on hosted Supabase it is not there (verified 2026-09-13), and this line is the
-- only thing that turns RLS on.
alter table public.merchants enable row level security;

-- Not covered by the primary key. private.current_merchant_ids() filters on this column, and once
-- business tables exist that call runs once per statement in every one of their policies.
create index if not exists merchants_owner_id_idx on public.merchants (owner_id);

-- These policies key on owner_id, NOT on private.current_merchant_ids(), and that is not an
-- oversight. docs/tenancy.md rule 3 governs *business* tables — the ones carrying a merchant_id
-- column. This is the tenant root itself, and routing its policies through the function that reads
-- the tenant root is the self-reference §3 flags under "the recursion trap".
--
-- When merchant_members arrives, only merchants_select_own changes:
--   using (id in (select private.current_merchant_ids()))
-- The three write policies stay on owner_id, and no business table moves.
drop policy if exists merchants_select_own on public.merchants;
create policy merchants_select_own on public.merchants
  for select to authenticated
  using ((select auth.uid()) = owner_id);

drop policy if exists merchants_insert_own on public.merchants;
create policy merchants_insert_own on public.merchants
  for insert to authenticated
  with check ((select auth.uid()) = owner_id);

-- Both clauses, for the same reason profiles_update_own carries both: `using` picks the rows,
-- `with check` picks what they may become. Without the second, a merchant can be handed to another
-- account by rewriting owner_id.
drop policy if exists merchants_update_own on public.merchants;
create policy merchants_update_own on public.merchants
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

-- Unlike profiles, merchants gets a delete policy: a user removing one of their own businesses is
-- an ordinary action, not account deletion.
drop policy if exists merchants_delete_own on public.merchants;
create policy merchants_delete_own on public.merchants
  for delete to authenticated
  using ((select auth.uid()) = owner_id);


-- The seam, and it ships with no caller on purpose.
--
-- Every business table added later gets policies of the shape
--   using (merchant_id in (select private.current_merchant_ids()))
-- and staff support then arrives by rewriting this function's body alone — zero policy rewrites,
-- zero table alterations. Writing it now is what stops the first business table shipping an
-- `auth.uid() = owner_id` policy "just for now", which is the rewrite-every-table cost
-- docs/tenancy.md §2 exists to avoid.
--
-- All three requirements from CLAUDE.md §6.2 are met: it lives in `private` so PostgREST publishes
-- no /rest/v1/rpc/ URL for it; search_path is pinned empty with a fully-qualified body, so a caller
-- cannot point an unqualified name at their own table and have it run as the owner; and the
-- (select auth.uid()) inside means it can only ever answer for its caller, however it is reached.
--
-- `stable` lets the planner call it once per statement instead of once per row.
create or replace function private.current_merchant_ids()
returns setof uuid
language sql
security definer
stable
set search_path = ''
as $$
  select m.id from public.merchants m where m.owner_id = (select auth.uid());
$$;

-- PUBLIC alone would not be enough: Supabase's default privileges grant EXECUTE on new functions to
-- anon, authenticated and service_role *directly*, so revoking from PUBLIC leaves three live grants
-- behind. All four names, every time.
revoke execute on function private.current_merchant_ids()
  from public, anon, authenticated, service_role;


-- ===== 20260910000000_merchants_contact_and_address.sql =====

-- CreateSystemModal revamp (revamps/Thu_09-10-2026_13.59.58.10): the wizard now collects seven
-- fields instead of four. Three of them land on public.merchants.
--
-- Every statement here is re-runnable, like the rest of supabase/migrations — `rename column` is
-- the one that is not idempotent on its own, so each is guarded by a catalog lookup rather than
-- `if not exists`, which ALTER ... RENAME does not accept.

-- 1. Store Description became Store Address.
--
-- A rename, not "add address, leave description behind". The field did not gain a sibling, it
-- changed meaning: the same one free-text box under the same 255 counter, now asking for where the
-- store is. Adding a column would leave `description` in the row shape forever, readable by
-- PostgREST, generated into database.types.ts, and answering "which one is live?" wrong for every
-- reader after today. A rename keeps the data and leaves nothing dead.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'merchants' and column_name = 'description'
  ) then
    alter table public.merchants rename column description to address;
    -- The constraint name is part of the error message a violation prints. Left as
    -- merchants_description_length it would name a column that no longer exists.
    alter table public.merchants rename constraint merchants_description_length to merchants_address_length;
  end if;
end
$$;

-- 2. The business contact email.
--
-- NOT a mirror of auth.users.email, and deliberately not on public.profiles. The reasoning that
-- keeps an email column off profiles (ARCHITECTURE.md — auth.users.email is the source of truth,
-- the client already holds it as session.user.email, a copy goes stale on the first address change)
-- is untouched by this: that is the *person's* sign-in address, this is the *business's* published
-- contact. They can differ, and one owner with two merchants can publish two of them, which is only
-- expressible on this table.
--
-- ponytail: nullable, because every merchant row that already exists was created before this field
-- did and there is nothing true to backfill them with. The form requires it for new rows
-- (src/features/merchants/schema.ts). Tighten to `not null` once the existing rows have one.
alter table public.merchants add column if not exists contact_email text;

-- 3. The phone number, stored as one E.164 string rather than a (dial code, national number) pair.
--
-- The wizard composes it from a country picker and one editable input, but what is worth keeping is
-- the number a person would dial. Splitting it across two columns would need both to be read and
-- rejoined at every call site, and the split is recoverable from the string anyway.
alter table public.merchants add column if not exists phone text;

-- Client-side Zod reports these before a round trip; these are what actually enforce them. Both
-- allow null, so they constrain the shape of a value without making the column required.
--
-- The email check is a length bound plus "has an @ with something before it" — deliberately not an
-- RFC 5322 regex. A regex strict enough to be worth writing rejects addresses that deliver, and one
-- loose enough not to is this check with more characters.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'merchants_contact_email_shape'
  ) then
    alter table public.merchants add constraint merchants_contact_email_shape
      check (
        contact_email is null
        or (length(contact_email) between 3 and 254 and position('@' in contact_email) > 1)
      );
  end if;

  -- E.164: a leading +, then 7 to 15 digits. Anything the user typed as spacing or punctuation is
  -- stripped on the client before it gets here, so this rejects a malformed number rather than a
  -- differently formatted one.
  if not exists (
    select 1 from pg_constraint where conname = 'merchants_phone_shape'
  ) then
    alter table public.merchants add constraint merchants_phone_shape
      check (phone is null or phone ~ '^\+[0-9]{7,15}$');
  end if;
end
$$;

-- No RLS line and no policies. This migration adds columns to a table that already has both, and
-- the four merchants_*_own policies key on owner_id — which is row-level, so a new column is
-- covered by them the moment it exists. A new *table* would need its own
-- `alter table … enable row level security` (CLAUDE.md §6.1); an altered one does not.


-- ===== 20260914092147_products.sql =====

-- Products: the first business table (System-Context/Merchant-Products-Screen), with the three
-- per-merchant lookups its form picks from — categories, tax classes, suppliers — and the six child
-- sets a product carries: rate tiers, operating hours, variant attributes, variants, bundle
-- components and custom fields.
--
-- Every table here carries a not-null merchant_id from this first migration (docs/tenancy.md rule 2)
-- and every policy keys on private.current_merchant_ids(), which gets its first caller today
-- (docs/tenancy.md rule 3). Re-runnable, like the rest of supabase/migrations.

create schema if not exists private;

-- 0. Let the policies below actually call the seam.
--
-- 20260908131200_merchants.sql revoked EXECUTE on current_merchant_ids() from authenticated, and
-- nothing granted USAGE on `private`. That was harmless while the function had no caller, but a
-- policy expression runs with the privileges of the role that issued the query — so every policy on
-- every table below would fail with "permission denied for schema private" (verified on the hosted
-- project 2026-09-14: both privileges false).
--
-- Granting them does not publish anything. PostgREST exposes `public` only, so a function in `private`
-- still has no /rest/v1/rpc/ URL, and the function answers for (select auth.uid()) alone — the other
-- two requirements of CLAUDE.md §6.2 carry the guarantee. The other functions in `private` keep their
-- EXECUTE revoked, so USAGE on the schema reaches none of them.
grant usage on schema private to authenticated;
grant execute on function private.current_merchant_ids() to authenticated;


-- 1. The currency a merchant's prices are shown in. ISO 4217 code, formatted on the client with
-- Intl.NumberFormat. Defaults to PHP because every existing merchant was set up with the Philippine
-- dial code first in the wizard; there is no setting UI for it yet.
alter table public.merchants add column if not exists currency text not null default 'PHP';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'merchants_currency_shape') then
    alter table public.merchants add constraint merchants_currency_shape check (currency ~ '^[A-Z]{3}$');
  end if;
end
$$;


-- 2. Enums. Each one generates a real union in src/lib/database.types.ts, which is what lets the form
-- index its label maps with no type assertion (the same trade store_category made). Adding a value
-- later is `alter type … add value` in a migration of its own.
do $$
begin
  if to_regtype('public.product_type') is null then
    create type public.product_type as enum ('stock', 'rental', 'bookable', 'flat');
  end if;
  if to_regtype('public.product_status') is null then
    create type public.product_status as enum ('draft', 'active', 'inactive', 'archived');
  end if;
  -- One list for Unit of Measure, Pricing Unit, purchase/usage units and duration units. Chosen fixed
  -- by the human over merchant-defined units, whose conversion factors between arbitrary custom
  -- units have no sensible meaning.
  if to_regtype('public.measure_unit') is null then
    create type public.measure_unit as enum (
      'piece', 'box', 'pack', 'kg', 'g', 'l', 'ml',
      'minute', 'hour', 'day', 'week', 'month', 'night', 'session'
    );
  end if;
  if to_regtype('public.duration_mode') is null then
    create type public.duration_mode as enum ('fixed_slot', 'flexible_range');
  end if;
  if to_regtype('public.rate_period') is null then
    create type public.rate_period as enum ('hour', 'day', 'week', 'month', 'night');
  end if;
  if to_regtype('public.custom_field_kind') is null then
    create type public.custom_field_kind as enum ('text', 'number', 'date', 'boolean');
  end if;
end
$$;


-- 3. Lookups.
--
-- Each has unique (id, merchant_id). That pair is what the product's foreign keys reference, so a
-- product can only ever point at a category, tax class or supplier of its own merchant — enforced by
-- the key itself, not by a policy that has to be remembered.

-- A subcategory is a category with a parent. ponytail: one level deep by convention — the picker only
-- offers top-level parents; a trigger enforcing depth is the upgrade if nesting ever appears.
create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  parent_id uuid,
  name text not null,
  created_at timestamptz not null default now(),

  constraint product_categories_id_merchant unique (id, merchant_id),
  constraint product_categories_parent_fk foreign key (parent_id, merchant_id)
    references public.product_categories (id, merchant_id) on delete cascade,
  constraint product_categories_not_own_parent check (parent_id is null or parent_id <> id),
  constraint product_categories_name_length check (length(btrim(name)) between 1 and 60),
  -- nulls not distinct, so two top-level categories (parent_id null) cannot share a name either.
  constraint product_categories_name_unique unique nulls not distinct (merchant_id, parent_id, name)
);

alter table public.product_categories enable row level security;
create index if not exists product_categories_merchant_id_idx on public.product_categories (merchant_id);
create index if not exists product_categories_parent_id_idx on public.product_categories (parent_id);

create table if not exists public.tax_classes (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  name text not null,
  rate numeric(5, 2) not null default 0,
  created_at timestamptz not null default now(),

  constraint tax_classes_id_merchant unique (id, merchant_id),
  constraint tax_classes_name_length check (length(btrim(name)) between 1 and 60),
  constraint tax_classes_rate_range check (rate between 0 and 100),
  constraint tax_classes_name_unique unique (merchant_id, name)
);

alter table public.tax_classes enable row level security;
create index if not exists tax_classes_merchant_id_idx on public.tax_classes (merchant_id);

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  name text not null,
  contact text,
  created_at timestamptz not null default now(),

  constraint suppliers_id_merchant unique (id, merchant_id),
  constraint suppliers_name_length check (length(btrim(name)) between 1 and 80),
  constraint suppliers_contact_length check (contact is null or length(contact) <= 255)
);

alter table public.suppliers enable row level security;
create index if not exists suppliers_merchant_id_idx on public.suppliers (merchant_id);


-- 4. Products.
--
-- One wide row rather than a table per type. The four types share General, Pricing, Media and
-- Advanced, and differ only in which of the inventory and availability columns are meaningful; a table
-- per type would need a union to list products at all. Columns a type does not use stay null.
--
-- Foreign keys use the default NO ACTION rather than RESTRICT on purpose: deleting a merchant cascades
-- to both its categories and its products in one statement, and RESTRICT checks immediately — before
-- the cascade has removed the products — where NO ACTION waits for the end of the statement.
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,

  -- General
  type public.product_type not null,
  name text not null,
  category_id uuid not null,
  subcategory_id uuid,
  sku text,
  barcode text,
  description text,
  tags text[] not null default '{}',
  status public.product_status not null default 'draft',
  sold_directly boolean not null default true,

  -- Pricing
  selling_price numeric(12, 2),
  cost_price numeric(12, 2),
  pricing_unit public.measure_unit,
  tax_class_id uuid,
  discountable boolean not null default true,
  deposit_amount numeric(12, 2),
  late_fee_per_hour numeric(12, 2),
  cancellation_fee numeric(12, 2),
  extra_unit_fee numeric(12, 2),

  -- Inventory (stock, rental)
  uom public.measure_unit,
  track_inventory boolean not null default true,
  qty_on_hand numeric(12, 3),
  reorder_threshold numeric(12, 3),
  reorder_qty numeric(12, 3),
  max_stock numeric(12, 3),
  storage_location text,
  supplier_id uuid,
  supplier_item_code text,
  lead_time_days integer,
  batch_tracking boolean not null default false,
  perishable boolean not null default false,
  shelf_life_days integer,
  expiry_date date,
  expiry_alert_days integer,
  purchase_unit public.measure_unit,
  usage_unit public.measure_unit,
  conversion_factor numeric(14, 4),

  -- Availability (rental, bookable)
  total_units integer,
  capacity_per_unit integer,
  duration_mode public.duration_mode,
  default_start_time time,
  default_end_time time,
  min_duration numeric(8, 2),
  min_duration_unit public.measure_unit,
  max_duration numeric(8, 2),
  max_duration_unit public.measure_unit,
  buffer_minutes integer,
  advance_window_days integer,
  blackout_dates date[] not null default '{}',
  overbooking_allowed boolean not null default false,

  -- Variants, recipe / bundle, advanced
  has_variants boolean not null default false,
  is_composite boolean not null default false,
  internal_notes text,

  -- The file name the Image-Pipeline brief stores (context/Image-Pipeline/packages.md §5). Written from
  -- this first migration so adding photos later is code only; nothing writes it yet.
  image_file text,

  -- PostgREST can filter a column against a value but not against another column, so "Low stock only"
  -- needs this spelled out. Stored, so the filter is a plain index-free equality on a small table.
  is_low_stock boolean generated always as (
    coalesce(track_inventory and qty_on_hand <= reorder_threshold, false)
  ) stored,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint products_id_merchant unique (id, merchant_id),
  constraint products_sku_unique unique (merchant_id, sku),
  constraint products_category_fk foreign key (category_id, merchant_id)
    references public.product_categories (id, merchant_id),
  constraint products_subcategory_fk foreign key (subcategory_id, merchant_id)
    references public.product_categories (id, merchant_id),
  -- The column list on SET NULL (Postgres 15+) nulls only the pointer. Without it the whole key pair
  -- would be nulled, merchant_id included, which the not-null constraint rejects.
  constraint products_tax_class_fk foreign key (tax_class_id, merchant_id)
    references public.tax_classes (id, merchant_id) on delete set null (tax_class_id),
  constraint products_supplier_fk foreign key (supplier_id, merchant_id)
    references public.suppliers (id, merchant_id) on delete set null (supplier_id),

  constraint products_name_length check (length(btrim(name)) between 1 and 120),
  constraint products_description_length check (description is null or length(description) <= 2000),
  constraint products_code_length check (
    (sku is null or length(sku) between 1 and 64) and (barcode is null or length(barcode) between 1 and 64)
  ),
  -- The spec's "Selling Price required if sold directly". A draft may be saved half-filled.
  constraint products_price_when_sold check (not sold_directly or status = 'draft' or selling_price is not null),
  constraint products_amounts_non_negative check (
    coalesce(selling_price, 0) >= 0 and coalesce(cost_price, 0) >= 0
    and coalesce(deposit_amount, 0) >= 0 and coalesce(late_fee_per_hour, 0) >= 0
    and coalesce(cancellation_fee, 0) >= 0 and coalesce(extra_unit_fee, 0) >= 0
    and coalesce(reorder_threshold, 0) >= 0 and coalesce(reorder_qty, 0) >= 0
    and coalesce(max_stock, 0) >= 0 and coalesce(total_units, 0) >= 0
    and coalesce(capacity_per_unit, 0) >= 0 and coalesce(buffer_minutes, 0) >= 0
    and coalesce(advance_window_days, 0) >= 0 and coalesce(lead_time_days, 0) >= 0
    and coalesce(shelf_life_days, 0) >= 0 and coalesce(expiry_alert_days, 0) >= 0
    and coalesce(min_duration, 0) >= 0 and coalesce(max_duration, 0) >= 0
  ),
  constraint products_conversion_positive check (conversion_factor is null or conversion_factor > 0)
);

alter table public.products enable row level security;
create index if not exists products_merchant_id_idx on public.products (merchant_id);
create index if not exists products_category_id_idx on public.products (category_id);
create index if not exists products_subcategory_id_idx on public.products (subcategory_id);
create index if not exists products_tax_class_id_idx on public.products (tax_class_id);
create index if not exists products_supplier_id_idx on public.products (supplier_id);


-- 5. The child sets. Each references (product_id, merchant_id), so a child row cannot belong to a
-- product of another merchant, and carries merchant_id itself so its policy is the same one-line shape
-- as every other business table rather than a join back to products.

create table if not exists public.product_rate_tiers (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  merchant_id uuid not null,
  position smallint not null default 0,
  period public.rate_period not null,
  price numeric(12, 2) not null,
  note text,

  constraint product_rate_tiers_product_fk foreign key (product_id, merchant_id)
    references public.products (id, merchant_id) on delete cascade,
  constraint product_rate_tiers_price_non_negative check (price >= 0),
  constraint product_rate_tiers_note_length check (note is null or length(note) <= 80)
);

alter table public.product_rate_tiers enable row level security;
create index if not exists product_rate_tiers_product_id_idx on public.product_rate_tiers (product_id, merchant_id);
create index if not exists product_rate_tiers_merchant_id_idx on public.product_rate_tiers (merchant_id);

create table if not exists public.product_operating_hours (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  merchant_id uuid not null,
  -- 0 = Sunday, matching Date.getDay() on the client.
  weekday smallint not null,
  opens time not null,
  closes time not null,

  constraint product_operating_hours_product_fk foreign key (product_id, merchant_id)
    references public.products (id, merchant_id) on delete cascade,
  constraint product_operating_hours_weekday_range check (weekday between 0 and 6),
  constraint product_operating_hours_order check (opens < closes),
  constraint product_operating_hours_one_per_day unique (product_id, weekday)
);

alter table public.product_operating_hours enable row level security;
create index if not exists product_operating_hours_merchant_id_idx on public.product_operating_hours (merchant_id);

create table if not exists public.product_variant_attributes (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  merchant_id uuid not null,
  position smallint not null default 0,
  name text not null,
  "values" text[] not null,

  constraint product_variant_attributes_product_fk foreign key (product_id, merchant_id)
    references public.products (id, merchant_id) on delete cascade,
  constraint product_variant_attributes_name_length check (length(btrim(name)) between 1 and 40),
  constraint product_variant_attributes_has_values check (cardinality("values") >= 1)
);

alter table public.product_variant_attributes enable row level security;
create index if not exists product_variant_attributes_product_id_idx on public.product_variant_attributes (product_id, merchant_id);
create index if not exists product_variant_attributes_merchant_id_idx on public.product_variant_attributes (merchant_id);

-- One row per attribute combination. qty_on_hand and barcode per variant were chosen by the human on
-- top of the spec's SKU and price delta.
create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  merchant_id uuid not null,
  position smallint not null default 0,
  label text not null,
  options text[] not null,
  sku text,
  barcode text,
  price_delta numeric(12, 2) not null default 0,
  qty_on_hand numeric(12, 3),

  constraint product_variants_product_fk foreign key (product_id, merchant_id)
    references public.products (id, merchant_id) on delete cascade,
  constraint product_variants_label_unique unique (product_id, label),
  constraint product_variants_code_length check (
    (sku is null or length(sku) between 1 and 64) and (barcode is null or length(barcode) between 1 and 64)
  ),
  constraint product_variants_qty_non_negative check (coalesce(qty_on_hand, 0) >= 0)
);

alter table public.product_variants enable row level security;
create index if not exists product_variants_merchant_id_idx on public.product_variants (merchant_id);

-- The bill of materials: product_id is the bundle, component_id the product it contains.
create table if not exists public.product_components (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  merchant_id uuid not null,
  position smallint not null default 0,
  component_id uuid not null,
  qty numeric(12, 3) not null,
  unit public.measure_unit,

  constraint product_components_product_fk foreign key (product_id, merchant_id)
    references public.products (id, merchant_id) on delete cascade,
  -- NO ACTION, not cascade: deleting a product that is inside a bundle fails (23503) instead of
  -- silently emptying the bundle. The client turns that into "used in a bundle" copy.
  constraint product_components_component_fk foreign key (component_id, merchant_id)
    references public.products (id, merchant_id),
  constraint product_components_not_self check (component_id <> product_id),
  constraint product_components_once unique (product_id, component_id),
  constraint product_components_qty_positive check (qty > 0)
);

alter table public.product_components enable row level security;
create index if not exists product_components_component_id_idx on public.product_components (component_id, merchant_id);
create index if not exists product_components_merchant_id_idx on public.product_components (merchant_id);

create table if not exists public.product_custom_fields (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  merchant_id uuid not null,
  position smallint not null default 0,
  label text not null,
  kind public.custom_field_kind not null default 'text',
  value text,

  constraint product_custom_fields_product_fk foreign key (product_id, merchant_id)
    references public.products (id, merchant_id) on delete cascade,
  constraint product_custom_fields_label_length check (length(btrim(label)) between 1 and 40),
  constraint product_custom_fields_value_length check (value is null or length(value) <= 500)
);

alter table public.product_custom_fields enable row level security;
create index if not exists product_custom_fields_product_id_idx on public.product_custom_fields (product_id, merchant_id);
create index if not exists product_custom_fields_merchant_id_idx on public.product_custom_fields (merchant_id);


-- 6. Policies. The same four on every table above, keyed on membership of the row's merchant
-- (docs/tenancy.md §3). Written as a loop because ten tables of forty hand-copied statements is where a
-- missing `with check` hides.
--
-- Scoped `to authenticated`; the function call wrapped in a select so the planner runs it once per
-- statement as an InitPlan; update carries both `using` and `with check`, so a row cannot be moved to
-- another merchant (CLAUDE.md §6.3).
do $$
declare
  t text;
begin
  foreach t in array array[
    'product_categories', 'tax_classes', 'suppliers', 'products',
    'product_rate_tiers', 'product_operating_hours', 'product_variant_attributes',
    'product_variants', 'product_components', 'product_custom_fields'
  ]
  loop
    execute format('drop policy if exists %I on public.%I', t || '_select_own_merchant', t);
    execute format(
      'create policy %I on public.%I for select to authenticated
         using (merchant_id in (select private.current_merchant_ids()))',
      t || '_select_own_merchant', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_insert_own_merchant', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated
         with check (merchant_id in (select private.current_merchant_ids()))',
      t || '_insert_own_merchant', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_update_own_merchant', t);
    execute format(
      'create policy %I on public.%I for update to authenticated
         using (merchant_id in (select private.current_merchant_ids()))
         with check (merchant_id in (select private.current_merchant_ids()))',
      t || '_update_own_merchant', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_delete_own_merchant', t);
    execute format(
      'create policy %I on public.%I for delete to authenticated
         using (merchant_id in (select private.current_merchant_ids()))',
      t || '_delete_own_merchant', t
    );
  end loop;
end
$$;


-- 7. The circular-bundle guard. A check constraint can see only its own row, so "A contains B contains
-- A" needs a walk: from the new component, follow what it contains, and fail if the walk reaches the
-- bundle being written. `union` (not `union all`) is what stops the walk on data that is already cyclic.
--
-- Security invoker: RLS already limits the walk to the caller's merchant, and the composite foreign keys
-- mean a cycle cannot cross merchants anyway. Execute revoked like every function in `private` —
-- Postgres checks a trigger function's EXECUTE when the trigger is created, not when it fires.
create or replace function private.assert_no_bundle_cycle()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if exists (
    with recursive reach (id) as (
      select new.component_id
      union
      select pc.component_id
      from public.product_components pc
      join reach r on pc.product_id = r.id
    )
    select 1 from reach where reach.id = new.product_id
  ) then
    -- The message is the stable part the client matches on; never shown to the user.
    raise exception 'product_components_cycle'
      using errcode = '23514', detail = 'A bundle cannot contain itself, directly or through another bundle.';
  end if;
  return new;
end;
$$;

revoke execute on function private.assert_no_bundle_cycle() from public, anon, authenticated, service_role;

drop trigger if exists product_components_no_cycle on public.product_components;
create trigger product_components_no_cycle
  before insert or update of product_id, component_id on public.product_components
  for each row execute function private.assert_no_bundle_cycle();


-- 8. save_product: the whole form in one transaction.
--
-- A product save touches up to seven tables. Written from the client as seven requests, a dropped
-- connection halfway leaves a product with half its variants; as one function call it lands whole or
-- not at all.
--
-- Security INVOKER, so none of CLAUDE.md §6.2's escalation applies: every statement inside runs as the
-- caller, and the policies above gate each one exactly as they would a direct request. It is in
-- `public` because it is meant to be called; anon is revoked because there is nothing for anon to save.
--
-- ponytail: the child sets are deleted and reinserted, which gives variants new ids on every save. Fine
-- while nothing references a variant; switch to keyed upserts when orders do.
create or replace function public.save_product(payload jsonb)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  p public.products;
  v_id uuid;
  v_merchant uuid;
begin
  p := jsonb_populate_record(null::public.products, payload -> 'product');

  if p.id is null then
    insert into public.products (
      merchant_id, type, name, category_id, subcategory_id, sku, barcode, description, tags, status,
      sold_directly, selling_price, cost_price, pricing_unit, tax_class_id, discountable,
      deposit_amount, late_fee_per_hour, cancellation_fee, extra_unit_fee,
      uom, track_inventory, qty_on_hand, reorder_threshold, reorder_qty, max_stock, storage_location,
      supplier_id, supplier_item_code, lead_time_days, batch_tracking, perishable, shelf_life_days,
      expiry_date, expiry_alert_days, purchase_unit, usage_unit, conversion_factor,
      total_units, capacity_per_unit, duration_mode, default_start_time, default_end_time,
      min_duration, min_duration_unit, max_duration, max_duration_unit, buffer_minutes,
      advance_window_days, blackout_dates, overbooking_allowed,
      has_variants, is_composite, internal_notes
    ) values (
      p.merchant_id, p.type, p.name, p.category_id, p.subcategory_id, p.sku, p.barcode, p.description,
      coalesce(p.tags, '{}'), coalesce(p.status, 'draft'),
      coalesce(p.sold_directly, true), p.selling_price, p.cost_price, p.pricing_unit, p.tax_class_id,
      coalesce(p.discountable, true),
      p.deposit_amount, p.late_fee_per_hour, p.cancellation_fee, p.extra_unit_fee,
      p.uom, coalesce(p.track_inventory, true), p.qty_on_hand, p.reorder_threshold, p.reorder_qty,
      p.max_stock, p.storage_location,
      p.supplier_id, p.supplier_item_code, p.lead_time_days, coalesce(p.batch_tracking, false),
      coalesce(p.perishable, false), p.shelf_life_days,
      p.expiry_date, p.expiry_alert_days, p.purchase_unit, p.usage_unit, p.conversion_factor,
      p.total_units, p.capacity_per_unit, p.duration_mode, p.default_start_time, p.default_end_time,
      p.min_duration, p.min_duration_unit, p.max_duration, p.max_duration_unit, p.buffer_minutes,
      p.advance_window_days, coalesce(p.blackout_dates, '{}'), coalesce(p.overbooking_allowed, false),
      coalesce(p.has_variants, false), coalesce(p.is_composite, false), p.internal_notes
    )
    returning id, merchant_id into v_id, v_merchant;
  else
    -- merchant_id is deliberately not in the SET list: a product does not move between merchants, and
    -- its child rows' composite keys would refuse it anyway.
    update public.products set
      type = p.type, name = p.name, category_id = p.category_id, subcategory_id = p.subcategory_id,
      sku = p.sku, barcode = p.barcode, description = p.description, tags = coalesce(p.tags, '{}'),
      status = coalesce(p.status, 'draft'), sold_directly = coalesce(p.sold_directly, true),
      selling_price = p.selling_price, cost_price = p.cost_price, pricing_unit = p.pricing_unit,
      tax_class_id = p.tax_class_id, discountable = coalesce(p.discountable, true),
      deposit_amount = p.deposit_amount, late_fee_per_hour = p.late_fee_per_hour,
      cancellation_fee = p.cancellation_fee, extra_unit_fee = p.extra_unit_fee,
      uom = p.uom, track_inventory = coalesce(p.track_inventory, true), qty_on_hand = p.qty_on_hand,
      reorder_threshold = p.reorder_threshold, reorder_qty = p.reorder_qty, max_stock = p.max_stock,
      storage_location = p.storage_location, supplier_id = p.supplier_id,
      supplier_item_code = p.supplier_item_code, lead_time_days = p.lead_time_days,
      batch_tracking = coalesce(p.batch_tracking, false), perishable = coalesce(p.perishable, false),
      shelf_life_days = p.shelf_life_days, expiry_date = p.expiry_date,
      expiry_alert_days = p.expiry_alert_days, purchase_unit = p.purchase_unit,
      usage_unit = p.usage_unit, conversion_factor = p.conversion_factor,
      total_units = p.total_units, capacity_per_unit = p.capacity_per_unit,
      duration_mode = p.duration_mode, default_start_time = p.default_start_time,
      default_end_time = p.default_end_time, min_duration = p.min_duration,
      min_duration_unit = p.min_duration_unit, max_duration = p.max_duration,
      max_duration_unit = p.max_duration_unit, buffer_minutes = p.buffer_minutes,
      advance_window_days = p.advance_window_days, blackout_dates = coalesce(p.blackout_dates, '{}'),
      overbooking_allowed = coalesce(p.overbooking_allowed, false),
      has_variants = coalesce(p.has_variants, false), is_composite = coalesce(p.is_composite, false),
      internal_notes = p.internal_notes, updated_at = now()
    where id = p.id
    returning id, merchant_id into v_id, v_merchant;

    -- RLS filters an UPDATE rather than refusing it, so another merchant's id updates zero rows.
    if v_id is null then
      raise exception 'product_not_found' using errcode = 'P0002';
    end if;
  end if;

  delete from public.product_rate_tiers where product_id = v_id;
  delete from public.product_operating_hours where product_id = v_id;
  delete from public.product_variant_attributes where product_id = v_id;
  delete from public.product_variants where product_id = v_id;
  delete from public.product_components where product_id = v_id;
  delete from public.product_custom_fields where product_id = v_id;

  insert into public.product_rate_tiers (product_id, merchant_id, position, period, price, note)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.period, x.price, x.note
  from jsonb_array_elements(coalesce(payload -> 'rate_tiers', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_rate_tiers, e.value) as x;

  insert into public.product_operating_hours (product_id, merchant_id, weekday, opens, closes)
  select v_id, v_merchant, x.weekday, x.opens, x.closes
  from jsonb_array_elements(coalesce(payload -> 'operating_hours', '[]')) as e (value)
  cross join lateral jsonb_populate_record(null::public.product_operating_hours, e.value) as x;

  insert into public.product_variant_attributes (product_id, merchant_id, position, name, "values")
  select v_id, v_merchant, (e.idx - 1)::smallint, x.name, x."values"
  from jsonb_array_elements(coalesce(payload -> 'variant_attributes', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variant_attributes, e.value) as x;

  insert into public.product_variants (
    product_id, merchant_id, position, label, options, sku, barcode, price_delta, qty_on_hand
  )
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, x.options, x.sku, x.barcode,
    coalesce(x.price_delta, 0), x.qty_on_hand
  from jsonb_array_elements(coalesce(payload -> 'variants', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variants, e.value) as x;

  insert into public.product_components (product_id, merchant_id, position, component_id, qty, unit)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.component_id, x.qty, x.unit
  from jsonb_array_elements(coalesce(payload -> 'components', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_components, e.value) as x;

  insert into public.product_custom_fields (product_id, merchant_id, position, label, kind, value)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, coalesce(x.kind, 'text'), x.value
  from jsonb_array_elements(coalesce(payload -> 'custom_fields', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_custom_fields, e.value) as x;

  return v_id;
end;
$$;

revoke execute on function public.save_product(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.save_product(jsonb) to authenticated;


-- ===== 20260917183630_resource_scopes.sql =====

-- The Resources split. The merchant shell's Products destination becomes three: Products (flat
-- services), Rentables (rental assets and bookable services) and Inventory (stock and consumables).
-- Each screen owns its own categories, and a product belongs to exactly one screen, decided by its
-- type. See .claude/context/System-History/version-13.1.md.
--
-- 1. category_scope, and a scope on every category.
-- 2. products.scope, generated from the type, so the category foreign keys can refuse a product
--    pointing at another screen's category.
-- 3. save_product stops changing a product's type: the screen it was created on decides it, and a
--    type change would move the product to another screen behind the merchant's back.


-- 1. Category scope. Three values, one per screen.
do $$
begin
  if to_regtype('public.category_scope') is null then
    create type public.category_scope as enum ('products', 'rentables', 'inventory');
  end if;
end
$$;

alter table public.product_categories add column if not exists scope public.category_scope;

-- The mapping this whole migration turns on: type -> screen. Written out at each use rather than as a
-- function: a function in `public` is a /rest/v1/rpc URL (CLAUDE.md §6.1), and the generated column
-- below cannot call one anyway.
--
-- A category serving two screens has no single right answer, so the migration stops rather than
-- guessing. Verified clean on the hosted project on 2026-09-18: every used category serves one scope.
do $$
begin
  if exists (
    select 1
    from public.products p
    join public.product_categories c on c.id in (p.category_id, p.subcategory_id)
    group by coalesce(c.parent_id, c.id)
    having count(distinct (p.type in ('rental', 'bookable'))) > 1
        or count(distinct (p.type = 'stock')) > 1
  ) then
    raise exception 'category_used_across_scopes'
      using detail = 'A category is used by two Resources screens; split it before applying.';
  end if;
end
$$;

-- Top-level categories take the scope of the products using them or their subcategories;
-- subcategories take their parent's; anything unused lands in Products.
update public.product_categories c
set scope = u.scope
from (
  select distinct coalesce(cat.parent_id, cat.id) as top_id,
    (case p.type
      when 'stock' then 'inventory'
      when 'rental' then 'rentables'
      when 'bookable' then 'rentables'
      else 'products'
    end)::public.category_scope as scope
  from public.products p
  join public.product_categories cat on cat.id in (p.category_id, p.subcategory_id)
) u
where c.id = u.top_id and c.scope is null;

update public.product_categories c set scope = coalesce(parent.scope, 'products')
from public.product_categories parent
where c.parent_id = parent.id and c.scope is null;

update public.product_categories set scope = 'products' where scope is null;

-- No default: a category written without a scope is a client bug, and should fail as one.
alter table public.product_categories alter column scope set not null;


-- 2. Product scope and the keys that use it. Dropped first and re-added, so the file re-runs.
--
-- A trigger, not a generated column: Postgres requires a generation expression to be immutable, and
-- every route from a literal to an enum value goes through enum_in, which is only stable
-- (`42P17: generation expression is not immutable`). The trigger writes the column on every insert
-- and on every change of type, so the client cannot set it to something else — the same guarantee,
-- one object further out.
alter table public.products add column if not exists scope public.category_scope;

create or replace function private.set_product_scope()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.scope := case new.type
    when 'stock' then 'inventory'
    when 'rental' then 'rentables'
    when 'bookable' then 'rentables'
    else 'products'
  end::public.category_scope;
  return new;
end;
$$;

revoke execute on function private.set_product_scope() from public, anon, authenticated, service_role;

drop trigger if exists set_product_scope on public.products;
create trigger set_product_scope
  before insert or update of type on public.products
  for each row execute function private.set_product_scope();

update public.products set scope = case type
  when 'stock' then 'inventory'
  when 'rental' then 'rentables'
  when 'bookable' then 'rentables'
  else 'products'
end::public.category_scope
where scope is null;

alter table public.products alter column scope set not null;

alter table public.products drop constraint if exists products_category_fk;
alter table public.products drop constraint if exists products_subcategory_fk;
alter table public.product_categories drop constraint if exists product_categories_parent_fk;
alter table public.product_categories drop constraint if exists product_categories_name_unique;
alter table public.product_categories drop constraint if exists product_categories_id_merchant_scope;

alter table public.product_categories
  add constraint product_categories_id_merchant_scope unique (id, merchant_id, scope);

-- A subcategory lives in its parent's scope.
alter table public.product_categories
  add constraint product_categories_parent_fk foreign key (parent_id, merchant_id, scope)
    references public.product_categories (id, merchant_id, scope) on delete cascade;

-- The same name may exist once per screen: "Drinks" in Products and "Drinks" in Inventory are two lists.
alter table public.product_categories
  add constraint product_categories_name_unique unique nulls not distinct (merchant_id, scope, parent_id, name);

-- NO ACTION, like the keys they replace. This is what stops a Rentables product pointing at an
-- Inventory category: the scope is derived from the type, so the pair simply has no row to reference.
alter table public.products
  add constraint products_category_fk foreign key (category_id, merchant_id, scope)
    references public.product_categories (id, merchant_id, scope);
alter table public.products
  add constraint products_subcategory_fk foreign key (subcategory_id, merchant_id, scope)
    references public.product_categories (id, merchant_id, scope);


-- 3. save_product, the writer for all three screens.
--
-- Changed from 20260914092147_products.sql in one place: `type` leaves the update list. A product is
-- created on one screen and stays there; changing its type would move it to another screen's list and
-- silently orphan its category, which the keys above would refuse anyway.
--
-- Everything else — security invoker, the child-set rewrite, the ponytail note on variant ids — is as
-- that file explains. Stock columns stay here: Inventory owns its products outright, so there is one
-- writer and nothing to race with.
create or replace function public.save_product(payload jsonb)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  p public.products;
  v_id uuid;
  v_merchant uuid;
begin
  p := jsonb_populate_record(null::public.products, payload -> 'product');

  if p.id is null then
    insert into public.products (
      merchant_id, type, name, category_id, subcategory_id, sku, barcode, description, tags, status,
      sold_directly, selling_price, cost_price, pricing_unit, tax_class_id, discountable,
      deposit_amount, late_fee_per_hour, cancellation_fee, extra_unit_fee,
      uom, track_inventory, qty_on_hand, reorder_threshold, reorder_qty, max_stock, storage_location,
      supplier_id, supplier_item_code, lead_time_days, batch_tracking, perishable, shelf_life_days,
      expiry_date, expiry_alert_days, purchase_unit, usage_unit, conversion_factor,
      total_units, capacity_per_unit, duration_mode, default_start_time, default_end_time,
      min_duration, min_duration_unit, max_duration, max_duration_unit, buffer_minutes,
      advance_window_days, blackout_dates, overbooking_allowed,
      has_variants, is_composite, internal_notes
    ) values (
      p.merchant_id, p.type, p.name, p.category_id, p.subcategory_id, p.sku, p.barcode, p.description,
      coalesce(p.tags, '{}'), coalesce(p.status, 'draft'),
      coalesce(p.sold_directly, true), p.selling_price, p.cost_price, p.pricing_unit, p.tax_class_id,
      coalesce(p.discountable, true),
      p.deposit_amount, p.late_fee_per_hour, p.cancellation_fee, p.extra_unit_fee,
      p.uom, coalesce(p.track_inventory, true), p.qty_on_hand, p.reorder_threshold, p.reorder_qty,
      p.max_stock, p.storage_location,
      p.supplier_id, p.supplier_item_code, p.lead_time_days, coalesce(p.batch_tracking, false),
      coalesce(p.perishable, false), p.shelf_life_days,
      p.expiry_date, p.expiry_alert_days, p.purchase_unit, p.usage_unit, p.conversion_factor,
      p.total_units, p.capacity_per_unit, p.duration_mode, p.default_start_time, p.default_end_time,
      p.min_duration, p.min_duration_unit, p.max_duration, p.max_duration_unit, p.buffer_minutes,
      p.advance_window_days, coalesce(p.blackout_dates, '{}'), coalesce(p.overbooking_allowed, false),
      coalesce(p.has_variants, false), coalesce(p.is_composite, false), p.internal_notes
    )
    returning id, merchant_id into v_id, v_merchant;
  else
    -- merchant_id and type are deliberately not in the SET list: a product does not move between
    -- merchants, and it does not move between Resources screens.
    update public.products set
      name = p.name, category_id = p.category_id, subcategory_id = p.subcategory_id,
      sku = p.sku, barcode = p.barcode, description = p.description, tags = coalesce(p.tags, '{}'),
      status = coalesce(p.status, 'draft'), sold_directly = coalesce(p.sold_directly, true),
      selling_price = p.selling_price, cost_price = p.cost_price, pricing_unit = p.pricing_unit,
      tax_class_id = p.tax_class_id, discountable = coalesce(p.discountable, true),
      deposit_amount = p.deposit_amount, late_fee_per_hour = p.late_fee_per_hour,
      cancellation_fee = p.cancellation_fee, extra_unit_fee = p.extra_unit_fee,
      uom = p.uom, track_inventory = coalesce(p.track_inventory, true), qty_on_hand = p.qty_on_hand,
      reorder_threshold = p.reorder_threshold, reorder_qty = p.reorder_qty, max_stock = p.max_stock,
      storage_location = p.storage_location, supplier_id = p.supplier_id,
      supplier_item_code = p.supplier_item_code, lead_time_days = p.lead_time_days,
      batch_tracking = coalesce(p.batch_tracking, false), perishable = coalesce(p.perishable, false),
      shelf_life_days = p.shelf_life_days, expiry_date = p.expiry_date,
      expiry_alert_days = p.expiry_alert_days, purchase_unit = p.purchase_unit,
      usage_unit = p.usage_unit, conversion_factor = p.conversion_factor,
      total_units = p.total_units, capacity_per_unit = p.capacity_per_unit,
      duration_mode = p.duration_mode, default_start_time = p.default_start_time,
      default_end_time = p.default_end_time, min_duration = p.min_duration,
      min_duration_unit = p.min_duration_unit, max_duration = p.max_duration,
      max_duration_unit = p.max_duration_unit, buffer_minutes = p.buffer_minutes,
      advance_window_days = p.advance_window_days, blackout_dates = coalesce(p.blackout_dates, '{}'),
      overbooking_allowed = coalesce(p.overbooking_allowed, false),
      has_variants = coalesce(p.has_variants, false), is_composite = coalesce(p.is_composite, false),
      internal_notes = p.internal_notes, updated_at = now()
    where id = p.id
    returning id, merchant_id into v_id, v_merchant;

    -- RLS filters an UPDATE rather than refusing it, so another merchant's id updates zero rows.
    if v_id is null then
      raise exception 'product_not_found' using errcode = 'P0002';
    end if;
  end if;

  delete from public.product_rate_tiers where product_id = v_id;
  delete from public.product_operating_hours where product_id = v_id;
  delete from public.product_variant_attributes where product_id = v_id;
  delete from public.product_variants where product_id = v_id;
  delete from public.product_components where product_id = v_id;
  delete from public.product_custom_fields where product_id = v_id;

  insert into public.product_rate_tiers (product_id, merchant_id, position, period, price, note)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.period, x.price, x.note
  from jsonb_array_elements(coalesce(payload -> 'rate_tiers', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_rate_tiers, e.value) as x;

  insert into public.product_operating_hours (product_id, merchant_id, weekday, opens, closes)
  select v_id, v_merchant, x.weekday, x.opens, x.closes
  from jsonb_array_elements(coalesce(payload -> 'operating_hours', '[]')) as e (value)
  cross join lateral jsonb_populate_record(null::public.product_operating_hours, e.value) as x;

  insert into public.product_variant_attributes (product_id, merchant_id, position, name, "values")
  select v_id, v_merchant, (e.idx - 1)::smallint, x.name, x."values"
  from jsonb_array_elements(coalesce(payload -> 'variant_attributes', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variant_attributes, e.value) as x;

  insert into public.product_variants (
    product_id, merchant_id, position, label, options, sku, barcode, price_delta, qty_on_hand
  )
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, x.options, x.sku, x.barcode,
    coalesce(x.price_delta, 0), x.qty_on_hand
  from jsonb_array_elements(coalesce(payload -> 'variants', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variants, e.value) as x;

  insert into public.product_components (product_id, merchant_id, position, component_id, qty, unit)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.component_id, x.qty, x.unit
  from jsonb_array_elements(coalesce(payload -> 'components', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_components, e.value) as x;

  insert into public.product_custom_fields (product_id, merchant_id, position, label, kind, value)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, coalesce(x.kind, 'text'), x.value
  from jsonb_array_elements(coalesce(payload -> 'custom_fields', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_custom_fields, e.value) as x;

  return v_id;
end;
$$;

revoke execute on function public.save_product(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.save_product(jsonb) to authenticated;
