-- GENERATED by tools/build-migrations.mjs from supabase/migrations/. Do not edit — run
-- `npm run build:migrations` instead (docs/migrations.md).
--
-- Every migration, oldest first. Each one is re-runnable, so this whole file can be pasted into the
-- dashboard's SQL Editor to build the schema on a fresh project.

-- ===== 20260902000002_profiles.sql =====

-- One row per user, created by a trigger so a profile always exists by the time the app reads
-- one, and deleted by the cascade when the account goes.

-- Holds functions that must never be reachable over HTTP: PostgREST publishes `public` (and
-- `graphql_public`) and nothing else, so a function in here has no /rest/v1/rpc/ URL to attack.
create schema if not exists private;

create table if not exists public.profiles (
  -- Not a key this schema chooses: it is auth.users.id. Random uuids fragment an index, but that
  -- trade was made in auth.users, and matching it is what lets `on delete cascade` do the cleanup.
  id uuid primary key references auth.users (id) on delete cascade,

  -- No `email` column on purpose. auth.users.email is the source of truth and the client already
  -- holds it as session.user.email; a copy here goes stale the moment someone changes their
  -- address, and keeping it in step needs a second trigger that nobody remembers to write.
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

-- Every table you add needs this line of its own. The next migration tries to install an event
-- trigger that would also catch it, but that needs superuser and hosted Supabase's `postgres` role is
-- not one — there it only warns and the trigger never exists (verified 2026-09-13), so it is no
-- substitute for writing the line. Without it PostgREST serves the whole table to anyone holding the
-- publishable key, which ships in the app bundle. The dashboard's Security Advisor flags the tables
-- that are missing it.
alter table public.profiles enable row level security;

-- Deliberately NOT `force row level security`, which is otherwise the stricter default worth
-- reaching for. Forcing it subjects the table owner to the policies too, and handle_new_user below
-- inserts as the owner during signup — a moment when there is no JWT, so auth.uid() is null and
-- profiles_insert_own would reject the row that signup exists to create.

-- Every policy is scoped `to authenticated` so it is never even evaluated for anon, and every
-- auth.uid() is wrapped in a select. Unwrapped, it is called once per row scanned; wrapped, the
-- planner runs it once as an InitPlan and reuses the result.
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select to authenticated
  using ((select auth.uid()) = id);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
  for insert to authenticated
  with check ((select auth.uid()) = id);

-- `using` decides which rows may be updated, `with check` what they may be updated *to*. Without
-- the second one a user could hand their row to somebody else by rewriting its id.
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- No delete policy, so no client can delete a profile directly. The row goes when the account
-- does, through the cascade on auth.users that delete_current_user below triggers.

-- No index on id: the primary key already is one.


-- Creates the profile row for a new signup.
--
-- security definer because the insert has to bypass RLS — see the note above about auth.uid()
-- being null inside the signup transaction — and because the caller here is GoTrue, not the user.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    -- Google and Facebook both land here through signInWithIdToken / the browser flow, and both
    -- populate these two keys. nullif keeps an empty string from masquerading as a set name.
    -- The jsonb ->> operator is in pg_catalog, so it still resolves under the empty search_path.
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke execute on function private.handle_new_user() from public, anon, authenticated, service_role;

-- Revoking EXECUTE does not stop this. Postgres checks EXECUTE on a trigger function when the
-- trigger is created, not each time it fires, so the trigger keeps working while the function
-- stays uncallable by hand.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();


-- Self-service account deletion, which the App Store requires of any app that can create an
-- account (Guideline 5.1.1(v)). Called from deleteAccount() in src/lib/auth.ts.
--
-- This one is in `public` because it is meant to be reachable — it is the app's own API, and
-- PostgREST only publishes `public`. Which is exactly why the grants below are not optional.
create or replace function public.delete_current_user()
returns void
language sql
security definer
set search_path = ''
as $$
  -- The only row this can ever touch is the caller's own. For an unauthenticated caller auth.uid()
  -- is null and `id = null` matches nothing, so the failure mode is deleting zero rows; the grant
  -- below is what actually keeps anon out. public.profiles goes with it through the cascade.
  delete from auth.users where id = (select auth.uid());
$$;

-- Without this, `create function` in a Supabase project leaves the function callable at
-- POST /rest/v1/rpc/delete_current_user by anyone holding the anon key — which ships inside the
-- app binary. Supabase's default privileges grant EXECUTE to anon, authenticated and service_role
-- directly, so all three have to be named; revoking from PUBLIC alone would not reach them.
revoke execute on function public.delete_current_user() from public, anon, authenticated, service_role;
grant execute on function public.delete_current_user() to authenticated;


-- ===== 20260902000003_rls_auto_enable.sql =====

-- Enables RLS automatically on every table created in `public` from here on.
--
-- This runs. It is a normal migration and `supabase db push` applies it.
--
--
-- What it does
--
-- Installs a DDL event trigger that runs `alter table ... enable row level security` on every table
-- created in `public` from then on. Forgetting that on one table is the most common way a Supabase
-- project leaks data: PostgREST publishes the table over HTTP the moment it exists, the publishable
-- key ships inside the app bundle where anyone can read it out, and with no policy in force every
-- row is world-readable.
--
--
-- It is a safety net, not the mechanism
--
-- Keep writing `alter table ... enable row level security` explicitly in every migration. Two
-- reasons this trigger cannot be relied on alone:
--
--   1. It needs superuser to install (see the DO block at the bottom), and on hosted Supabase it
--      does NOT install. The project's `postgres` role is not a superuser (`rolsuper` is false), so
--      `create event trigger` fails with `permission denied to create event trigger` — verified on
--      this project's hosted database on 2026-09-13. The block turns that into a warning, so
--      `supabase db push` succeeds, the SQL Editor reports "Success", and the trigger is simply not
--      there. private.rls_auto_enable() below is still created, with nothing calling it. The
--      trigger only exists on a local `supabase start` stack, so on a hosted project the explicit
--      line is the only thing that turns RLS on.
--   2. It is invisible. `\d your_table` does not mention it, the migration that created that table
--      does not mention it, and nothing leads a reader from an unexpectedly empty result back to
--      this file.
--
-- RLS with no policies is deny-all, so when it does fire the failure mode is a query returning
-- nothing — loud, and one `create policy` away from fixed.
--
--
-- What still reports the gap
--
-- The dashboard's Security Advisor (Advisors -> Security) reports `rls_disabled_in_public` for any
-- table this missed. `supabase db lint` is NOT this — that command only type-checks plpgsql.

create schema if not exists private;

-- The function lives in `private`, not `public`. PostgREST only publishes `public` (and
-- `graphql_public`), so nothing in here has a /rest/v1/rpc/ URL at all. The revoke below is a
-- second lock on the same door.
create or replace function private.rls_auto_enable()
returns event_trigger
language plpgsql
security definer
-- Pinned, and the body fully qualified because of it. An unqualified name inside a security
-- definer function resolves against the *caller's* search_path, so a caller who creates their own
-- `format` or their own table and points the path at it gets that object executed with this
-- function's owner privileges. Empty is safe for the calls below: pg_catalog is searched
-- implicitly even when it is not on the path.
set search_path = ''
as $$
declare
  cmd record;
begin
  for cmd in
    select *
    from pg_catalog.pg_event_trigger_ddl_commands()
    where object_type in ('table', 'partitioned table')
      and schema_name = 'public'
  loop
    begin
      -- object_identity arrives already schema-qualified and quoted, so %s is right here and %I
      -- would quote it a second time.
      execute pg_catalog.format('alter table %s enable row level security', cmd.object_identity);
    exception
      -- An event trigger that raises aborts the CREATE TABLE that fired it. A table that resists
      -- RLS is worth a warning, not a migration that cannot run.
      when others then
        raise warning 'rls_auto_enable: could not enable RLS on %', cmd.object_identity;
    end;
  end loop;
end;
$$;

-- Not redundant with the schema choice. Supabase ships default privileges that grant EXECUTE on
-- new functions to anon, authenticated and service_role *directly* — not through PUBLIC — so
-- revoking from PUBLIC alone would leave three live grants behind.
revoke execute on function private.rls_auto_enable() from public, anon, authenticated, service_role;

-- CREATE EVENT TRIGGER requires superuser. The local `supabase start` stack has it; hosted Supabase's
-- `postgres` role does not, so on a hosted project this block always lands in the exception branch.
-- That must not take the whole migration down: every table's own migration enables RLS explicitly,
-- so this is defence in depth where it installs, not the only defence.
do $$
begin
  execute 'drop event trigger if exists ensure_rls';
  execute 'create event trigger ensure_rls on ddl_command_end
             when tag in (''CREATE TABLE'', ''CREATE TABLE AS'', ''SELECT INTO'')
             execute function private.rls_auto_enable()';
exception
  when insufficient_privilege then
    raise warning
      'ensure_rls not installed: creating an event trigger needs superuser. Every table still sets RLS explicitly.';
end;
$$;


-- ===== 20260908000000_drop_legacy_catalog_functions.sql =====

-- Drop the leftover book-catalog functions.
--
-- The hosted project this repo points at was previously used by an unrelated library
-- catalog app. Its tables are already gone, but nine functions survived in `public`
-- with no caller and no dependent object: `pg_trigger` holds only this project's own
-- `on_auth_user_created`, and `fn_set_updated_at` is attached to nothing.
--
-- They are not dead weight only. `public` is the schema PostgREST publishes, so each
-- one was a live `/rest/v1/rpc/<name>` URL reachable with the publishable key that
-- ships inside the app bundle. Three were `security definer` with `execute` still
-- granted to `anon`:
--
--   * `verify_user_password` (both overloads) answered password guesses without a
--     session — an unauthenticated credential-testing endpoint.
--   * `insert_book_encrypted` wrote rows as the owner.
--
-- None of the nine pinned `search_path`, so an unqualified name in the body resolved
-- against the caller's — the escalation CLAUDE.md section 6.2 rule 2 describes.
--
-- `if exists` because a clone pointed at a fresh Supabase project never had these,
-- and `supabase db push` has to succeed there too. No `cascade`: if some object does
-- turn out to depend on one of these, this migration should fail loudly rather than
-- take that object with it.
--
-- No revert file (docs/migrations.md rule 2): the bodies of what this drops are not in
-- the repo, and restoring them would reopen the endpoints described above.
-- no-revert: drop-only; its revert would restore leftover functions from an unrelated project

drop function if exists public.verify_user_password(p_email text, p_password text, p_enc_key text);
drop function if exists public.verify_user_password(p_email_fingerprint text, p_password text);
drop function if exists public.insert_book_encrypted(
  p_enc_key text, p_title text, p_responsibility text, p_variant_title text,
  p_parallel_title text, p_main_creator text, p_contributors text, p_corporate text,
  p_place_of_publication text, p_publisher text, p_date_of_publication text,
  p_extent_of_text text, p_edition text, p_illustration text, p_series text,
  p_isbn text, p_subject_typical text, p_subject_personal text,
  p_call_number_prefix text, p_call_number text, p_material_types text[],
  p_accession text, p_language text, p_library_location text,
  p_electronic_access text, p_cover_image_file text, p_vol_copy integer,
  p_entered_by text, p_date_entered date, p_update_date date, p_vocabulary text,
  p_localization text, p_collection_types text[]
);
drop function if exists public.encrypt_field(plaintext text, enc_key text);
drop function if exists public.decrypt_field(ciphertext bytea, enc_key text);
drop function if exists public.hash_password(plain text);
drop function if exists public.verify_password(plain text, stored_hash text);
drop function if exists public.sha256_hex(val text);
drop function if exists public.fn_set_updated_at();


-- ===== 20260908131200_merchants.sql =====

-- The tenant table. A merchant is the business whose rows are being protected; a user account is a
-- person. Today one merchant has exactly one user, and `merchants.owner_id` *is* the membership —
-- see docs/tenancy.md §3 for why `merchant_members` is deliberately not built yet.
--
-- This is also the answer to the open question in docs/tenancy.md §5, "who creates the merchant
-- row?": not a trigger. An explicit onboarding step — CreateSystemModal in
-- src/features/merchants/ — because a staff member joining an existing merchant must not silently
-- create a second one.

-- Already created by 20260902000002_profiles.sql. Repeated because a migration that depends on a
-- schema should say so rather than inherit it by file ordering.
create schema if not exists private;

-- An enum rather than `text` + a check constraint. Both cost one migration to add a value and both
-- need the same data migration to remove one, so the tie is broken by what reaches the client:
-- an enum generates a real union in src/lib/database.types.ts, which is what lets
-- CATEGORY_META[row.category] compile with no type assertion. `text` generates `string`, which
-- forces exactly the assertion .oxlintrc.json rejects (require-safety-comment-for-type-assertion,
-- no-unsafe-dictionary-type).
--
-- Adding a category later is `alter type public.store_category add value '…'` in a migration of its
-- own: Postgres will not let the same transaction use a value it just added.
do $$
begin
  if not exists (
    select 1 from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'store_category' and n.nspname = 'public'
  ) then
    create type public.store_category as enum (
      'restaurant', 'cafe', 'clothing', 'grocery', 'bakery',
      'electronics', 'pharmacy', 'bookstore', 'fitness', 'other'
    );
  end if;
end
$$;

create table if not exists public.merchants (
  id uuid primary key default gen_random_uuid(),

  -- The cascade is what makes public.delete_current_user() complete: deleting the auth.users row
  -- takes the profile and every merchant with it, so account deletion needs no extra statement.
  owner_id uuid not null references auth.users (id) on delete cascade,

  name text not null,
  description text,
  category public.store_category not null,
  created_at timestamptz not null default now(),

  -- btrim so a name of pure whitespace fails. The 255 on description is the number the
  -- CreateSystemModal counter shows the user; the same bound lives in
  -- src/features/merchants/schema.ts so the form reports it before a round trip, and here so the
  -- database is the one that actually enforces it.
  constraint merchants_name_length check (length(btrim(name)) between 1 and 80),
  constraint merchants_description_length check (description is null or length(description) <= 255)
);

-- Its own line, per the note in 20260902000002_profiles.sql. The event trigger in
-- 20260902000003_rls_auto_enable.sql would also catch this table where it installs, but installing it
-- needs superuser — so on hosted Supabase it is not there (verified 2026-09-13), and this line is the
-- only thing that turns RLS on.
alter table public.merchants enable row level security;

-- Not covered by the primary key. private.current_merchant_ids() filters on this column, and once
-- business tables exist that call runs once per statement in every one of their policies.
create index if not exists merchants_owner_id_idx on public.merchants (owner_id);

-- These policies key on owner_id, NOT on private.current_merchant_ids(), and that is not an
-- oversight. docs/tenancy.md rule 3 governs *business* tables — the ones carrying a merchant_id
-- column. This is the tenant root itself, and routing its policies through the function that reads
-- the tenant root is the self-reference §3 flags under "the recursion trap".
--
-- When merchant_members arrives, only merchants_select_own changes:
--   using (id in (select private.current_merchant_ids()))
-- The three write policies stay on owner_id, and no business table moves.
drop policy if exists merchants_select_own on public.merchants;
create policy merchants_select_own on public.merchants
  for select to authenticated
  using ((select auth.uid()) = owner_id);

drop policy if exists merchants_insert_own on public.merchants;
create policy merchants_insert_own on public.merchants
  for insert to authenticated
  with check ((select auth.uid()) = owner_id);

-- Both clauses, for the same reason profiles_update_own carries both: `using` picks the rows,
-- `with check` picks what they may become. Without the second, a merchant can be handed to another
-- account by rewriting owner_id.
drop policy if exists merchants_update_own on public.merchants;
create policy merchants_update_own on public.merchants
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

-- Unlike profiles, merchants gets a delete policy: a user removing one of their own businesses is
-- an ordinary action, not account deletion.
drop policy if exists merchants_delete_own on public.merchants;
create policy merchants_delete_own on public.merchants
  for delete to authenticated
  using ((select auth.uid()) = owner_id);


-- The seam, and it ships with no caller on purpose.
--
-- Every business table added later gets policies of the shape
--   using (merchant_id in (select private.current_merchant_ids()))
-- and staff support then arrives by rewriting this function's body alone — zero policy rewrites,
-- zero table alterations. Writing it now is what stops the first business table shipping an
-- `auth.uid() = owner_id` policy "just for now", which is the rewrite-every-table cost
-- docs/tenancy.md §2 exists to avoid.
--
-- All three requirements from CLAUDE.md §6.2 are met: it lives in `private` so PostgREST publishes
-- no /rest/v1/rpc/ URL for it; search_path is pinned empty with a fully-qualified body, so a caller
-- cannot point an unqualified name at their own table and have it run as the owner; and the
-- (select auth.uid()) inside means it can only ever answer for its caller, however it is reached.
--
-- `stable` lets the planner call it once per statement instead of once per row.
create or replace function private.current_merchant_ids()
returns setof uuid
language sql
security definer
stable
set search_path = ''
as $$
  select m.id from public.merchants m where m.owner_id = (select auth.uid());
$$;

-- PUBLIC alone would not be enough: Supabase's default privileges grant EXECUTE on new functions to
-- anon, authenticated and service_role *directly*, so revoking from PUBLIC leaves three live grants
-- behind. All four names, every time.
revoke execute on function private.current_merchant_ids()
  from public, anon, authenticated, service_role;


-- ===== 20260910000000_merchants_contact_and_address.sql =====

-- CreateSystemModal revamp (revamps/Thu_09-10-2026_13.59.58.10): the wizard now collects seven
-- fields instead of four. Three of them land on public.merchants.
--
-- Every statement here is re-runnable, like the rest of supabase/migrations — `rename column` is
-- the one that is not idempotent on its own, so each is guarded by a catalog lookup rather than
-- `if not exists`, which ALTER ... RENAME does not accept.

-- 1. Store Description became Store Address.
--
-- A rename, not "add address, leave description behind". The field did not gain a sibling, it
-- changed meaning: the same one free-text box under the same 255 counter, now asking for where the
-- store is. Adding a column would leave `description` in the row shape forever, readable by
-- PostgREST, generated into database.types.ts, and answering "which one is live?" wrong for every
-- reader after today. A rename keeps the data and leaves nothing dead.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'merchants' and column_name = 'description'
  ) then
    alter table public.merchants rename column description to address;
    -- The constraint name is part of the error message a violation prints. Left as
    -- merchants_description_length it would name a column that no longer exists.
    alter table public.merchants rename constraint merchants_description_length to merchants_address_length;
  end if;
end
$$;

-- 2. The business contact email.
--
-- NOT a mirror of auth.users.email, and deliberately not on public.profiles. The reasoning that
-- keeps an email column off profiles (ARCHITECTURE.md — auth.users.email is the source of truth,
-- the client already holds it as session.user.email, a copy goes stale on the first address change)
-- is untouched by this: that is the *person's* sign-in address, this is the *business's* published
-- contact. They can differ, and one owner with two merchants can publish two of them, which is only
-- expressible on this table.
--
-- ponytail: nullable, because every merchant row that already exists was created before this field
-- did and there is nothing true to backfill them with. The form requires it for new rows
-- (src/features/merchants/schema.ts). Tighten to `not null` once the existing rows have one.
alter table public.merchants add column if not exists contact_email text;

-- 3. The phone number, stored as one E.164 string rather than a (dial code, national number) pair.
--
-- The wizard composes it from a country picker and one editable input, but what is worth keeping is
-- the number a person would dial. Splitting it across two columns would need both to be read and
-- rejoined at every call site, and the split is recoverable from the string anyway.
alter table public.merchants add column if not exists phone text;

-- Client-side Zod reports these before a round trip; these are what actually enforce them. Both
-- allow null, so they constrain the shape of a value without making the column required.
--
-- The email check is a length bound plus "has an @ with something before it" — deliberately not an
-- RFC 5322 regex. A regex strict enough to be worth writing rejects addresses that deliver, and one
-- loose enough not to is this check with more characters.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'merchants_contact_email_shape'
  ) then
    alter table public.merchants add constraint merchants_contact_email_shape
      check (
        contact_email is null
        or (length(contact_email) between 3 and 254 and position('@' in contact_email) > 1)
      );
  end if;

  -- E.164: a leading +, then 7 to 15 digits. Anything the user typed as spacing or punctuation is
  -- stripped on the client before it gets here, so this rejects a malformed number rather than a
  -- differently formatted one.
  if not exists (
    select 1 from pg_constraint where conname = 'merchants_phone_shape'
  ) then
    alter table public.merchants add constraint merchants_phone_shape
      check (phone is null or phone ~ '^\+[0-9]{7,15}$');
  end if;
end
$$;

-- No RLS line and no policies. This migration adds columns to a table that already has both, and
-- the four merchants_*_own policies key on owner_id — which is row-level, so a new column is
-- covered by them the moment it exists. A new *table* would need its own
-- `alter table … enable row level security` (CLAUDE.md §6.1); an altered one does not.
