-- GENERATED by tools/build-migrations.mjs from supabase/reverts/. Do not edit — run
-- `npm run build:migrations` instead (docs/migrations.md).
--
-- DESTROYS DATA. Every revert, newest first, which takes the schema back to nothing. A migration
-- marked `-- no-revert:` has no block here.

-- ===== 20260914092147_products.sql =====

-- Reverts 20260914000000_products.sql.
--
-- DESTROYS DATA: every product, category, tax class and supplier of every merchant, with all their
-- rate tiers, operating hours, variants, components and custom fields. merchants.currency goes too.
--
-- The app expects the new shape — src/features/products, src/features/categories,
-- src/features/tax-classes, src/features/suppliers and src/lib/database.types.ts all name it — so
-- regenerate the types after running this.
--
-- Newest revert, so nothing has to run before it (docs/migrations.md rule 6).

drop function if exists public.save_product(jsonb);

-- Dropping product_components takes its trigger with it; the function is dropped after the table.
drop table if exists public.product_custom_fields;
drop table if exists public.product_components;
drop table if exists public.product_variants;
drop table if exists public.product_variant_attributes;
drop table if exists public.product_operating_hours;
drop table if exists public.product_rate_tiers;
drop table if exists public.products;
drop table if exists public.suppliers;
drop table if exists public.tax_classes;
drop table if exists public.product_categories;

drop function if exists private.assert_no_bundle_cycle();

-- After the tables whose columns use them.
drop type if exists public.custom_field_kind;
drop type if exists public.rate_period;
drop type if exists public.duration_mode;
drop type if exists public.measure_unit;
drop type if exists public.product_status;
drop type if exists public.product_type;

alter table if exists public.merchants drop constraint if exists merchants_currency_shape;
alter table if exists public.merchants drop column if exists currency;

-- Back to how 20260908131200_merchants.sql left the seam: no caller, no grant.
do $$
begin
  if to_regprocedure('private.current_merchant_ids()') is not null then
    revoke execute on function private.current_merchant_ids() from authenticated;
  end if;
end
$$;
revoke usage on schema private from authenticated;


-- ===== 20260910000000_merchants_contact_and_address.sql =====

-- Reverts 20260910000000_merchants_contact_and_address.sql.
--
-- DESTROYS DATA: every merchant's contact_email and phone go with their columns. address is renamed
-- back to description, so what it holds survives.
--
-- The app expects the new shape — src/features/merchants/schema.ts and src/lib/database.types.ts
-- name all three columns — so regenerate the types after running this.
--
-- Newest revert, so nothing has to run before it. supabase/all-in-one/revert.sql orders every revert
-- newest first (docs/migrations.md).

-- Dropping a column takes its check constraint with it. Named anyway, so this file reads as the exact
-- inverse of the one it undoes.
alter table if exists public.merchants drop constraint if exists merchants_phone_shape;
alter table if exists public.merchants drop constraint if exists merchants_contact_email_shape;

alter table if exists public.merchants drop column if exists phone;
alter table if exists public.merchants drop column if exists contact_email;

-- Guarded by a catalog lookup for the same reason the forward rename is: ALTER ... RENAME COLUMN
-- accepts no `if exists`.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'merchants' and column_name = 'address'
  ) then
    alter table public.merchants rename column address to description;
    alter table public.merchants rename constraint merchants_address_length to merchants_description_length;
  end if;
end
$$;


-- ===== 20260908131200_merchants.sql =====

-- Reverts 20260908131200_merchants.sql.
--
-- DESTROYS DATA: every merchant row goes with the table. auth.users and public.profiles are untouched.
--
-- Run the revert of 20260910000000_merchants_contact_and_address.sql first. No statement below uses
-- `cascade`, so a business table added later — one whose foreign key or policy points at this table
-- or at current_merchant_ids() — makes this fail loudly until its own revert has run, rather than
-- being dropped without anyone naming it.

drop function if exists private.current_merchant_ids();

-- Its four policies, the owner_id index, both check constraints and the primary key go with it.
drop table if exists public.merchants;

-- After the table, whose category column is what depends on the type.
drop type if exists public.store_category;

-- Schema `private` stays: 20260902000002_profiles.sql created it, and that migration's revert is the
-- one that removes it.


-- ===== 20260902000003_rls_auto_enable.sql =====

-- Reverts 20260902000003_rls_auto_enable.sql.
--
-- Destroys no data. Tables created afterwards stop getting RLS enabled automatically — which every
-- migration already does explicitly anyway (CLAUDE.md §6.1).
--
-- Run the reverts of every newer migration first; supabase/all-in-one/revert.sql already does.

-- Dropping an event trigger needs superuser, the same as creating one. On a hosted project where the
-- forward migration could not install it there is nothing to drop, so warn and continue rather than
-- stopping the rest of the revert.
do $$
begin
  execute 'drop event trigger if exists ensure_rls';
exception
  when insufficient_privilege then
    raise warning 'ensure_rls not dropped: dropping an event trigger needs superuser.';
end;
$$;

-- After the trigger, which depends on this function. If the trigger exists but could not be dropped
-- above, this fails — correctly, since the function is still in use.
drop function if exists private.rls_auto_enable();


-- ===== 20260902000002_profiles.sql =====

-- Reverts 20260902000002_profiles.sql — the oldest migration, so its revert runs last.
--
-- DESTROYS DATA: every profile row goes with the table. The accounts in auth.users are NOT deleted —
-- this migration never created them — but new signups stop getting a profile, and the RPC behind the
-- Delete account button stops existing.
--
-- Every newer revert must run first. The final `drop schema` fails while any object is still in
-- `private`, and that failure is the check that they did.

drop trigger if exists on_auth_user_created on auth.users;

-- After the trigger that calls it.
drop function if exists private.handle_new_user();

drop function if exists public.delete_current_user();

-- Its three policies and primary key go with it. The foreign key lives on this side, so auth.users
-- itself is untouched.
drop table if exists public.profiles;

-- No `cascade`: if the rls_auto_enable or merchants revert was skipped, their functions are still in
-- here and this fails instead of dropping them unnamed.
drop schema if exists private;
