-- GENERATED by tools/build-migrations.mjs from supabase/reverts/. Do not edit — run
-- `npm run build:migrations` instead (docs/migrations.md).
--
-- DESTROYS DATA. Every revert, newest first, which takes the schema back to nothing. A migration
-- marked `-- no-revert:` has no block here.

-- ===== 20260917183630_resource_scopes.sql =====

-- Reverts 20260917120000_resource_scopes.sql.
--
-- Destroys data: only the scope of each category. Categories, products and stock counts all stay.
-- It fails on purpose if two Resources screens each hold a category with the same name under the same
-- parent. The old unique key allowed one name per parent across every screen; rename one before
-- reverting.
--
-- The app expects the scoped shape (src/features/products/resources.ts, the three Resources screens),
-- so regenerate src/lib/database.types.ts after running this.
--
-- Newest revert, so nothing has to run before it (docs/migrations.md rule 6).

drop trigger if exists set_product_scope on public.products;
drop function if exists private.set_product_scope();

alter table if exists public.products drop constraint if exists products_subcategory_fk;
alter table if exists public.products drop constraint if exists products_category_fk;
alter table if exists public.product_categories drop constraint if exists product_categories_name_unique;
alter table if exists public.product_categories drop constraint if exists product_categories_parent_fk;
alter table if exists public.product_categories drop constraint if exists product_categories_id_merchant_scope;

alter table if exists public.products drop column if exists scope;
alter table if exists public.product_categories drop column if exists scope;
drop type if exists public.category_scope;

-- Back to the keys 20260914092147_products.sql created.
alter table public.product_categories
  add constraint product_categories_parent_fk foreign key (parent_id, merchant_id)
    references public.product_categories (id, merchant_id) on delete cascade;
alter table public.product_categories
  add constraint product_categories_name_unique unique nulls not distinct (merchant_id, parent_id, name);
alter table public.products
  add constraint products_category_fk foreign key (category_id, merchant_id)
    references public.product_categories (id, merchant_id);
alter table public.products
  add constraint products_subcategory_fk foreign key (subcategory_id, merchant_id)
    references public.product_categories (id, merchant_id);

-- save_product as 20260914092147_products.sql wrote it: `type` writable again on update.
create or replace function public.save_product(payload jsonb)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  p public.products;
  v_id uuid;
  v_merchant uuid;
begin
  p := jsonb_populate_record(null::public.products, payload -> 'product');

  if p.id is null then
    insert into public.products (
      merchant_id, type, name, category_id, subcategory_id, sku, barcode, description, tags, status,
      sold_directly, selling_price, cost_price, pricing_unit, tax_class_id, discountable,
      deposit_amount, late_fee_per_hour, cancellation_fee, extra_unit_fee,
      uom, track_inventory, qty_on_hand, reorder_threshold, reorder_qty, max_stock, storage_location,
      supplier_id, supplier_item_code, lead_time_days, batch_tracking, perishable, shelf_life_days,
      expiry_date, expiry_alert_days, purchase_unit, usage_unit, conversion_factor,
      total_units, capacity_per_unit, duration_mode, default_start_time, default_end_time,
      min_duration, min_duration_unit, max_duration, max_duration_unit, buffer_minutes,
      advance_window_days, blackout_dates, overbooking_allowed,
      has_variants, is_composite, internal_notes
    ) values (
      p.merchant_id, p.type, p.name, p.category_id, p.subcategory_id, p.sku, p.barcode, p.description,
      coalesce(p.tags, '{}'), coalesce(p.status, 'draft'),
      coalesce(p.sold_directly, true), p.selling_price, p.cost_price, p.pricing_unit, p.tax_class_id,
      coalesce(p.discountable, true),
      p.deposit_amount, p.late_fee_per_hour, p.cancellation_fee, p.extra_unit_fee,
      p.uom, coalesce(p.track_inventory, true), p.qty_on_hand, p.reorder_threshold, p.reorder_qty,
      p.max_stock, p.storage_location,
      p.supplier_id, p.supplier_item_code, p.lead_time_days, coalesce(p.batch_tracking, false),
      coalesce(p.perishable, false), p.shelf_life_days,
      p.expiry_date, p.expiry_alert_days, p.purchase_unit, p.usage_unit, p.conversion_factor,
      p.total_units, p.capacity_per_unit, p.duration_mode, p.default_start_time, p.default_end_time,
      p.min_duration, p.min_duration_unit, p.max_duration, p.max_duration_unit, p.buffer_minutes,
      p.advance_window_days, coalesce(p.blackout_dates, '{}'), coalesce(p.overbooking_allowed, false),
      coalesce(p.has_variants, false), coalesce(p.is_composite, false), p.internal_notes
    )
    returning id, merchant_id into v_id, v_merchant;
  else
    -- merchant_id is deliberately not in the SET list: a product does not move between merchants, and
    -- its child rows' composite keys would refuse it anyway.
    update public.products set
      type = p.type, name = p.name, category_id = p.category_id, subcategory_id = p.subcategory_id,
      sku = p.sku, barcode = p.barcode, description = p.description, tags = coalesce(p.tags, '{}'),
      status = coalesce(p.status, 'draft'), sold_directly = coalesce(p.sold_directly, true),
      selling_price = p.selling_price, cost_price = p.cost_price, pricing_unit = p.pricing_unit,
      tax_class_id = p.tax_class_id, discountable = coalesce(p.discountable, true),
      deposit_amount = p.deposit_amount, late_fee_per_hour = p.late_fee_per_hour,
      cancellation_fee = p.cancellation_fee, extra_unit_fee = p.extra_unit_fee,
      uom = p.uom, track_inventory = coalesce(p.track_inventory, true), qty_on_hand = p.qty_on_hand,
      reorder_threshold = p.reorder_threshold, reorder_qty = p.reorder_qty, max_stock = p.max_stock,
      storage_location = p.storage_location, supplier_id = p.supplier_id,
      supplier_item_code = p.supplier_item_code, lead_time_days = p.lead_time_days,
      batch_tracking = coalesce(p.batch_tracking, false), perishable = coalesce(p.perishable, false),
      shelf_life_days = p.shelf_life_days, expiry_date = p.expiry_date,
      expiry_alert_days = p.expiry_alert_days, purchase_unit = p.purchase_unit,
      usage_unit = p.usage_unit, conversion_factor = p.conversion_factor,
      total_units = p.total_units, capacity_per_unit = p.capacity_per_unit,
      duration_mode = p.duration_mode, default_start_time = p.default_start_time,
      default_end_time = p.default_end_time, min_duration = p.min_duration,
      min_duration_unit = p.min_duration_unit, max_duration = p.max_duration,
      max_duration_unit = p.max_duration_unit, buffer_minutes = p.buffer_minutes,
      advance_window_days = p.advance_window_days, blackout_dates = coalesce(p.blackout_dates, '{}'),
      overbooking_allowed = coalesce(p.overbooking_allowed, false),
      has_variants = coalesce(p.has_variants, false), is_composite = coalesce(p.is_composite, false),
      internal_notes = p.internal_notes, updated_at = now()
    where id = p.id
    returning id, merchant_id into v_id, v_merchant;

    -- RLS filters an UPDATE rather than refusing it, so another merchant's id updates zero rows.
    if v_id is null then
      raise exception 'product_not_found' using errcode = 'P0002';
    end if;
  end if;

  delete from public.product_rate_tiers where product_id = v_id;
  delete from public.product_operating_hours where product_id = v_id;
  delete from public.product_variant_attributes where product_id = v_id;
  delete from public.product_variants where product_id = v_id;
  delete from public.product_components where product_id = v_id;
  delete from public.product_custom_fields where product_id = v_id;

  insert into public.product_rate_tiers (product_id, merchant_id, position, period, price, note)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.period, x.price, x.note
  from jsonb_array_elements(coalesce(payload -> 'rate_tiers', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_rate_tiers, e.value) as x;

  insert into public.product_operating_hours (product_id, merchant_id, weekday, opens, closes)
  select v_id, v_merchant, x.weekday, x.opens, x.closes
  from jsonb_array_elements(coalesce(payload -> 'operating_hours', '[]')) as e (value)
  cross join lateral jsonb_populate_record(null::public.product_operating_hours, e.value) as x;

  insert into public.product_variant_attributes (product_id, merchant_id, position, name, "values")
  select v_id, v_merchant, (e.idx - 1)::smallint, x.name, x."values"
  from jsonb_array_elements(coalesce(payload -> 'variant_attributes', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variant_attributes, e.value) as x;

  insert into public.product_variants (
    product_id, merchant_id, position, label, options, sku, barcode, price_delta, qty_on_hand
  )
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, x.options, x.sku, x.barcode,
    coalesce(x.price_delta, 0), x.qty_on_hand
  from jsonb_array_elements(coalesce(payload -> 'variants', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variants, e.value) as x;

  insert into public.product_components (product_id, merchant_id, position, component_id, qty, unit)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.component_id, x.qty, x.unit
  from jsonb_array_elements(coalesce(payload -> 'components', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_components, e.value) as x;

  insert into public.product_custom_fields (product_id, merchant_id, position, label, kind, value)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, coalesce(x.kind, 'text'), x.value
  from jsonb_array_elements(coalesce(payload -> 'custom_fields', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_custom_fields, e.value) as x;

  return v_id;
end;
$$;

revoke execute on function public.save_product(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.save_product(jsonb) to authenticated;


-- ===== 20260914092147_products.sql =====

-- Reverts 20260914000000_products.sql.
--
-- DESTROYS DATA: every product, category, tax class and supplier of every merchant, with all their
-- rate tiers, operating hours, variants, components and custom fields. merchants.currency goes too.
--
-- The app expects the new shape — src/features/products, src/features/categories,
-- src/features/tax-classes, src/features/suppliers and src/lib/database.types.ts all name it — so
-- regenerate the types after running this.
--
-- Newest revert, so nothing has to run before it (docs/migrations.md rule 6).

drop function if exists public.save_product(jsonb);

-- Dropping product_components takes its trigger with it; the function is dropped after the table.
drop table if exists public.product_custom_fields;
drop table if exists public.product_components;
drop table if exists public.product_variants;
drop table if exists public.product_variant_attributes;
drop table if exists public.product_operating_hours;
drop table if exists public.product_rate_tiers;
drop table if exists public.products;
drop table if exists public.suppliers;
drop table if exists public.tax_classes;
drop table if exists public.product_categories;

drop function if exists private.assert_no_bundle_cycle();

-- After the tables whose columns use them.
drop type if exists public.custom_field_kind;
drop type if exists public.rate_period;
drop type if exists public.duration_mode;
drop type if exists public.measure_unit;
drop type if exists public.product_status;
drop type if exists public.product_type;

alter table if exists public.merchants drop constraint if exists merchants_currency_shape;
alter table if exists public.merchants drop column if exists currency;

-- Back to how 20260908131200_merchants.sql left the seam: no caller, no grant.
do $$
begin
  if to_regprocedure('private.current_merchant_ids()') is not null then
    revoke execute on function private.current_merchant_ids() from authenticated;
  end if;
end
$$;
revoke usage on schema private from authenticated;


-- ===== 20260910000000_merchants_contact_and_address.sql =====

-- Reverts 20260910000000_merchants_contact_and_address.sql.
--
-- DESTROYS DATA: every merchant's contact_email and phone go with their columns. address is renamed
-- back to description, so what it holds survives.
--
-- The app expects the new shape — src/features/merchants/schema.ts and src/lib/database.types.ts
-- name all three columns — so regenerate the types after running this.
--
-- Newest revert, so nothing has to run before it. supabase/all-in-one/revert.sql orders every revert
-- newest first (docs/migrations.md).

-- Dropping a column takes its check constraint with it. Named anyway, so this file reads as the exact
-- inverse of the one it undoes.
alter table if exists public.merchants drop constraint if exists merchants_phone_shape;
alter table if exists public.merchants drop constraint if exists merchants_contact_email_shape;

alter table if exists public.merchants drop column if exists phone;
alter table if exists public.merchants drop column if exists contact_email;

-- Guarded by a catalog lookup for the same reason the forward rename is: ALTER ... RENAME COLUMN
-- accepts no `if exists`.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'merchants' and column_name = 'address'
  ) then
    alter table public.merchants rename column address to description;
    alter table public.merchants rename constraint merchants_address_length to merchants_description_length;
  end if;
end
$$;


-- ===== 20260908131200_merchants.sql =====

-- Reverts 20260908131200_merchants.sql.
--
-- DESTROYS DATA: every merchant row goes with the table. auth.users and public.profiles are untouched.
--
-- Run the revert of 20260910000000_merchants_contact_and_address.sql first. No statement below uses
-- `cascade`, so a business table added later — one whose foreign key or policy points at this table
-- or at current_merchant_ids() — makes this fail loudly until its own revert has run, rather than
-- being dropped without anyone naming it.

drop function if exists private.current_merchant_ids();

-- Its four policies, the owner_id index, both check constraints and the primary key go with it.
drop table if exists public.merchants;

-- After the table, whose category column is what depends on the type.
drop type if exists public.store_category;

-- Schema `private` stays: 20260902000002_profiles.sql created it, and that migration's revert is the
-- one that removes it.


-- ===== 20260902000003_rls_auto_enable.sql =====

-- Reverts 20260902000003_rls_auto_enable.sql.
--
-- Destroys no data. Tables created afterwards stop getting RLS enabled automatically — which every
-- migration already does explicitly anyway (CLAUDE.md §6.1).
--
-- Run the reverts of every newer migration first; supabase/all-in-one/revert.sql already does.

-- Dropping an event trigger needs superuser, the same as creating one. On a hosted project where the
-- forward migration could not install it there is nothing to drop, so warn and continue rather than
-- stopping the rest of the revert.
do $$
begin
  execute 'drop event trigger if exists ensure_rls';
exception
  when insufficient_privilege then
    raise warning 'ensure_rls not dropped: dropping an event trigger needs superuser.';
end;
$$;

-- After the trigger, which depends on this function. If the trigger exists but could not be dropped
-- above, this fails — correctly, since the function is still in use.
drop function if exists private.rls_auto_enable();


-- ===== 20260902000002_profiles.sql =====

-- Reverts 20260902000002_profiles.sql — the oldest migration, so its revert runs last.
--
-- DESTROYS DATA: every profile row goes with the table. The accounts in auth.users are NOT deleted —
-- this migration never created them — but new signups stop getting a profile, and the RPC behind the
-- Delete account button stops existing.
--
-- Every newer revert must run first. The final `drop schema` fails while any object is still in
-- `private`, and that failure is the check that they did.

drop trigger if exists on_auth_user_created on auth.users;

-- After the trigger that calls it.
drop function if exists private.handle_new_user();

drop function if exists public.delete_current_user();

-- Its three policies and primary key go with it. The foreign key lives on this side, so auth.users
-- itself is untouched.
drop table if exists public.profiles;

-- No `cascade`: if the rls_auto_enable or merchants revert was skipped, their functions are still in
-- here and this fails instead of dropping them unnamed.
drop schema if exists private;
